const EventHelper= {
    NAME : "EventHelper",
    ON_MOUSE_BEGAN : "onMouseBegan",
    ON_KB_BEGAN : "onKbBegan",
    ON_MOUSE_MOVE : "onMouseMove",
    ON_MOUSE_END : "onMouseEnd",
    ON_KB_END : "onKbEnd",
    ON_MOUSE_CANCEL : "onMouseCancel",
    ON_KB_CANCEL : "onKbCancel",
    ON_MOUSE_OUT : "onMouseOut",
    ON_MOUSE_OVER : "onMouseOver",
    ON_SCROLL : "onScroll",
    ON_CLICK : "onClick",
    ON_SWIPE_LEFT : "onSwipeLeft",
    ON_SWIPE_RIGHT : "onSwipeRight",
    ON_SWIPE_UP : "onSwipeUp",
    ON_SWIPE_DOWN : "onSwipeDown",
    CLICK_OFFSET : 20,
    TIME_OFFSET : 250,
    SWIPE_OFFSET : 10,
    lastMousePos: null,
}